FROM node:10

WORKDIR /usr/src/app

COPY *.json ./
COPY src ./src
COPY public ./public
COPY server ./server
COPY .env.server ./

RUN npm install
RUN npm run build:ssr

EXPOSE 3001

CMD npm run serve:ssr
