FROM node:10

WORKDIR /usr/src/app

COPY *.json ./
COPY *.js ./
COPY pages ./pages
COPY public ./public
COPY components ./components
COPY util ./util

RUN npm install
RUN npm run build

EXPOSE 3002

CMD npm run start
