FROM node:10

WORKDIR /usr/src/app

COPY *.json ./
COPY *.js ./
COPY src ./src
COPY public ./public
COPY .env.production ./.env

RUN npm install
RUN npm run build:client

EXPOSE 5001

CMD npm run serve:csr
